id = "mdx"
name = "MDX"
description = "MDX support"
version = "0.1.0"
schema_version = 1
authors = ["Suhail Razzak <suhail.razzak@gmail.com>"]
repository = "https://github.com/srazzak/zed-mdx"

[language_servers.mdx-language-server]
name = "MDX Language Server"
language = "MDX"

[grammars.mdx]
repository = "https://github.com/srazzak/tree-sitter-mdx"
rev = "9d7385fcfd5def3c24e09edcc5fad4af4ac28ed6"
