name = "MDX"
grammar = "mdx"
path_suffixes = ["mdx"]
autoclose_before = ">}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = true, newline = true },
    { start = "</", end = ">", close = true, newline = true },
]
# See https://clojure.org/reference/reader#_reader_forms
tab_size = 4
